version: "3.8"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 21204444
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # server : mysql
  # user : root
  # pass : 21204444
  # db : just throw anything

        # phpmyadmin:
        #   image: phpmyadmin:5.2.1-apache
        #   ports:
        #     - 8080:80
        #   restart: always
        #   environment:
        #     PMA_HOST: mysql
        #     PMA_USER: root
        #     PMA_PASSWORD: 21204444
        #   depends_on:
        #     - mysql

volumes:
  mysql-data:
