version: "3.7"
services:
  mysql:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 21204444
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports:
      - 8080:80
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 21204444
    depends_on:
      - mysql

volumes:
  mysql-data:
